from app.repositories.base import BaseRepository
from app.repositories.gmail_account_repo import (
    FabricGmailAccountRepository,
    GmailAccountRepository,
    PostgresGmailAccountRepository,
    get_gmail_account_repository,
)
from app.repositories.known_domain_repo import (
    FabricKnownDomainRepository,
    KnownDomainRepository,
    PostgresKnownDomainRepository,
    get_known_domain_repository,
)
from app.repositories.user_repo import (
    FabricUserRepository,
    PostgresUserRepository,
    UserRepository,
    get_user_repository,
)
from app.repositories.signal_repo import (
    SignalRepository,
    FabricSignalRepository,
    PostgresSignalRepository,
    get_signal_repository,
    SignalThreadRepository,
    FabricSignalThreadRepository,
    PostgresSignalThreadRepository,
    get_signal_thread_repository,
    SignalAttachmentRepository,
    FabricSignalAttachmentRepository,
    PostgresSignalAttachmentRepository,
    get_signal_attachment_repository,
)
from app.repositories.signal_category_repo import (
    SignalCategoryRepository,
    FabricSignalCategoryRepository,
    PostgresSignalCategoryRepository,
    get_signal_category_repository,
)
from app.repositories.signal_entity_repo import (
    EntityRepository,
    FabricEntityRepository,
    PostgresEntityRepository,
    get_entity_repository,
    SignalEntityRepository,
    FabricSignalEntityRepository,
    PostgresSignalEntityRepository,
    get_signal_entity_repository,
    EntityTimelineEventRepository,
    FabricEntityTimelineEventRepository,
    PostgresEntityTimelineEventRepository,
    get_entity_timeline_event_repository,
)
from app.repositories.signal_embedding_repo import (
    SignalEmbeddingRepository,
    FabricSignalEmbeddingRepository,
    PostgresSignalEmbeddingRepository,
    get_signal_embedding_repository,
)
from app.repositories.sender_profile_repo import (
    SenderProfileRepository,
    FabricSenderProfileRepository,
    PostgresSenderProfileRepository,
    get_sender_profile_repository,
)
from app.repositories.behavior_interaction_repo import (
    BehaviorInteractionRepository,
    FabricBehaviorInteractionRepository,
    PostgresBehaviorInteractionRepository,
    get_behavior_interaction_repository,
)
from app.repositories.ask_signal_history_repo import (
    AskSignalHistoryRepository,
    FabricAskSignalHistoryRepository,
    PostgresAskSignalHistoryRepository,
    get_ask_signal_history_repository,
)

__all__ = [
    "BaseRepository",
    "UserRepository",
    "FabricUserRepository",
    "PostgresUserRepository",
    "get_user_repository",
    "KnownDomainRepository",
    "FabricKnownDomainRepository",
    "PostgresKnownDomainRepository",
    "get_known_domain_repository",
    "GmailAccountRepository",
    "FabricGmailAccountRepository",
    "PostgresGmailAccountRepository",
    "get_gmail_account_repository",
    "SignalRepository",
    "FabricSignalRepository",
    "PostgresSignalRepository",
    "get_signal_repository",
    "SignalThreadRepository",
    "FabricSignalThreadRepository",
    "PostgresSignalThreadRepository",
    "get_signal_thread_repository",
    "SignalAttachmentRepository",
    "FabricSignalAttachmentRepository",
    "PostgresSignalAttachmentRepository",
    "get_signal_attachment_repository",
    "SignalCategoryRepository",
    "FabricSignalCategoryRepository",
    "PostgresSignalCategoryRepository",
    "get_signal_category_repository",
    "EntityRepository",
    "FabricEntityRepository",
    "PostgresEntityRepository",
    "get_entity_repository",
    "SignalEntityRepository",
    "FabricSignalEntityRepository",
    "PostgresSignalEntityRepository",
    "get_signal_entity_repository",
    "EntityTimelineEventRepository",
    "FabricEntityTimelineEventRepository",
    "PostgresEntityTimelineEventRepository",
    "get_entity_timeline_event_repository",
    "SignalEmbeddingRepository",
    "FabricSignalEmbeddingRepository",
    "PostgresSignalEmbeddingRepository",
    "get_signal_embedding_repository",
    "SenderProfileRepository",
    "FabricSenderProfileRepository",
    "PostgresSenderProfileRepository",
    "get_sender_profile_repository",
    "BehaviorInteractionRepository",
    "FabricBehaviorInteractionRepository",
    "PostgresBehaviorInteractionRepository",
    "get_behavior_interaction_repository",
    "AskSignalHistoryRepository",
    "FabricAskSignalHistoryRepository",
    "PostgresAskSignalHistoryRepository",
    "get_ask_signal_history_repository",
]


